[package]
name = "advent-of-code-2021-05-01"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "day_2021_05_1"
path = "src/day_2021_05_1.rs"

[dependencies]
log = "0.4.14"
env_logger = "0.9.0"
regex = "1.5.4"
